config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :contacts, only: [:new, :create]

  devise_for :users
  resources :blogs

  authenticate :users do
    mount Sidekiq::Web => '/sidekiq'
  end

  root "contacts#new"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  def self.search(search)
    columns = %w{title tags body}
    self.where(
      columns
      .map {|c| "#{c} ILIKE :search" }
      .join(' OR '),
    search: "%#{search}%"
    )
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_presence_of :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:search]
      @blogs = Blog.search(params[:search]).paginate(page: params[:page], per_page: 2).order("created_at DESC")
    else
      @blogs = Blog.all.paginate(page: params[:page], per_page: 2).order('created_at DESC')
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      flash[:success] = "Successfully Created!"
      redirect_to blog_path(@blog.id)
    else
      render :new
      flash[:error] = "Hmmm... Somthing went wrong."
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:title,:tags, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactWorker.perform_async(@contact.id)
      flash[:success] = "Your message was sent. Thank you, I will touch bases with you as soon as possible!"
      redirect_to root_path
    else
      render :new
      flash[:error] = "Opps..If you can't send the message you can send me an email!"
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when "alert" then "alert alert-danger"
    when "success" then "alert alert-success"
    when "error" then "alert alert-warning"
    end
  end
end

app/helpers/blogs_helper.rb
require 'redcarpet'
require 'rexml/parsers/pullparser'

module BlogsHelper

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div(line_numbers: :table)
    end
  end

  def markdown(blog_body)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(blog_body).html_safe
  end
end

app/views/blogs/_blog.html.erb
<div class="post-title">
  <h1><%= link_to "#{blog.title}",  blog_path(blog.id) %></h1>
</div>
<div class="post-info">
  <span><%= blog.created_at.strftime("%B %d, %Y") %></span>
</div>
<%= truncate(strip_tags(markdown(blog.body)), length: 500) %>
<br/>
<%= link_to "Read More",  blog_path(blog.id), class: 'button button-style button-anim fa fa-long-arrow-right'%>

app/views/blogs/index.html.erb
<div id="main">
  <div class="container">
    <div class="row">
      <%= render('shared/sidenav') %>

      <div class="col-lg-9 col-md-9">
        <div class="col-md-12 page-body">

          <div class="sub-title">
            <h2>KevBlogs</h2>
            <div class="search-form">
              <%= form_tag request.path, method: :get, enforce_utf8: false do %>
                <%= text_field_tag :search, params[:search], class: "form-control search-input", placeholder: "Find a blog!" %>
              <% end %>
            </div>
          </div>

          <div class="col-md-12 content-page">
            <div class="col-lg-12 col-md-12 blog-post">
              <div id="blogs">
                <% if @blogs.any? %>
                  <%= render @blogs %>
                <% else %>
                  <h2 style="text-align: center;">Sorry, I have not blogged about <%= params[:search] %> yet.</h2>
                <% end %>
              </div>
            </div>
          </div>

          <div id="infinite-scrolling">
            <%= will_paginate(@blogs, digest: false) %>
          </div>

        </div>
        <%= render('shared/blogfooter') %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/index.js.erb
$('#blogs').append('<%= j render @blogs %>');
<% if @blogs.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @blogs %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/blogs/new.html.erb
<div class='container'>
  <%= form_for @blog do |f| %>

    <div class="row">
      <div class="col-lg-6">
        <div class="input-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <div class="input-group">
          <%= f.label :tags %>
          <%= f.text_field :tags, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <div class="input-group">
          <%= f.label :body %>
          <%= f.text_area :body, class: 'form-control' %>
        </div>
      </div>
    </div>

    <%= f.submit "Add Blog", class: ''%>
  <% end %>
</div>

app/views/blogs/show.html.erb
<div id="main">
  <div class="container">
    <div class="row">
      <%= render('shared/sidenav') %>

      <div class="col-lg-9 col-md-9">
        <div class="col-md-12 page-body">

          <div class="sub-title">
            <%= link_to "Back", blogs_path %>
          </div>

          <div class="col-md-12 content-page">
            <div class="col-lg-12 col-md-12 blog-post">

              <div class="post-title">
                <h1><%= @blog.title %></h1>
              </div>
              <div class="post-info">
                <span><%= "#{@blog.created_at.strftime("%B %d, %Y")}/ by Kevin Finley" %></span>
              </div>

                <p><%= markdown(@blog.body)%></p>

              <h2>Discussion</h2>
              <%# TODO intergrate comments %>
              <%# TODO load pagination %>
              <hr/>

              <h2>You maybe like</h2>
              <%# TODO recommendations %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/_footer.html.erb
<section id="contact">
  <div class="contact-section">
    <div class="container text-center">
      <br>
      <h2>Contact Me</h2>
      <p>Feel free to shout me a message by filling out the contact form.</p>
      <div class="row">
        <div class="col-lg-6 col-sm-12">
          <%= render('contacts/form') %>
        </div>

        <div class="col-lg-6 col-sm-12">
          <br>
          <h3>Email</h3>
          <p>kftwotwo@gmail.com</p><br>
          <h3>Phone</h3>
          <p>(541)-508-6597</p><br>
          <h3>My Social Sites</h3>
          <div id="even-pad" class="col-lg-12">
            <a href="https://twitter.com/kftwotwo" target="_blank" class="btn btn-outline-info"><i class="fa fa-twitter"> <span class="network-name">Twitter</span></i></a>
            <a href="https://github.com/kftwotwo" target="_blank" class="btn btn-outline-secondary"><i class="fa fa-github"> <span class="network-name">GitHub</span></i></a>
          </div>

          <div class="col-lg-12">
            <a href="https://www.linkedin.com/in/kftwotwo/" target="_blank" class="btn btn-outline-primary"><i class="fa fa-linkedin-square"> <span class="network-name">Linkedin</span></i></a>
            <a href="https://kftwotwo.github.io" target="_blank" class="btn btn-outline-primary"><span class="network-name">KevBlog</span></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <hr>
    <a href="https://github.com/kftwotwo/new-portfolio" target="_blank" class="white-text">Resource</a>
  </div>
</section>

app/views/contacts/_form.html.erb
<%= form_for @contact, class: 'form-horizontal' do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group ">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: 'btn'%>
<% end %>

app/views/contacts/_projects.html.erb
<section id="projects">
  <div class="portfolio">
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 project-card">
        <img src="https://dl.dropboxusercontent.com/s/vqbzudx1ngoxgcn/text-adventure.png?dl=0" alt="Text Adventure Page" class="project-image"/>
        <div class="project_images_overlay text-center">
          <h6>Text Adventure</h6>
          <p class="project-description">JavaScript, CSS, jQuery</p>
          <a href="https://kftwotwo.github.io/group-text-adventure/" target="_blank" class="btn btn-primary">Play it!</a>
          <a href="https://github.com/kftwotwo/group-text-adventure" target="_blank" class="btn btn-info">View Source</a>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 project-card">
        <img src="https://dl.dropboxusercontent.com/s/5r4qjoe13x6hxc1/gummi-bear-kingdom.png?dl=0" alt="Gummi Bear King Page" class="project-image"/>
        <div class="project_images_overlay text-center">
          <h6>Gummi Bear Kingdom</h6>
          <p class="project-description">Ruby on Rails, CSS</p>
          <a href="https://gummi-bear-kingdom-kevin.herokuapp.com/" target="_blank" class="btn btn-primary">View Live</a>
          <a href="https://github.com/kftwotwo/gummi-bear-kingdom" target="_blank" class="btn btn-info">View Source</a>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 project-card">
        <img src="https://dl.dropboxusercontent.com/s/avaeegm1t5igvmy/code-notes.png?dl=0" alt="Code Notes Page" class="project-image"/>
        <div class="project_images_overlay text-center">
          <h6>Code Notes</h6>
          <p class="project-description">Ruby, JavaScript, OAuth</p>
          <a href="http://code-note-kevin.herokuapp.com/" target="_blank" class="btn btn-primary">View Live</a>
          <a href="https://github.com/DiegoSPB/coding_notes" target="_blank" class="btn btn-info">View Source</a>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 project-card">
        <img src="https://dl.dropboxusercontent.com/s/gjwsvy0vrope9ql/coming_soon.png?dl=0" alt="Coming Soon" class="project-image"/>
        <div class="project_images_overlay text-center">
          <h6>Billtracker</h6>
          <p class="project-description">Ruby on Rails, CoffeeScript</p>
          <a href="https://github.com/kftwotwo/billtracker" target="_blank" class="btn btn-info">View Source</a>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/contacts/_time-line.html.erb
<section id="timeline">
  <div class="tl-item">
    <div class="tl-bg" style="background-image: url(https://placeimg.com/801/801/nature)"></div>
    <div class="tl-year">
      <p class="f2 heading--sanSerif">2012-2014</p>
    </div>

    <div class="tl-content">
      <h1>Milligans IGA</h1>
      <p>Milligans IGA was a small town grocery store in Absarokee Montana. This was my first real job previously I was a ranch hand. I rode my bike for 12 miles each day to work until I was able to afford a vehicle. I learned how to stock shelves and perform customer care for the elderly. This job helped me network. People would ask me to lend them a extra hand or odd jobs.</p>
    </div>
  </div>

  <div class="tl-item">
    <div class="tl-bg" style="background-image: url(https://dl.dropboxusercontent.com/s/pkjtkrejsosxk1z/welding.jpeg?dl=0)"></div>
    <div class="tl-year">
      <p class="f2 heading--sanSerif">2013-2016</p>
    </div>

    <div class="tl-content">
      <h1 class="f3 text--accent ttu">Infinite Machine Inc.</h1>
      <p>Infinite Machine was an industrial grade welding and fabricating facility that specialized in heavy equipment for local mines. While I was working at Milligans IGA I got a part time job offer to learn how to weld. Later that year I gave my two week notice at Milligans IGA because Infinite Machine offered me a full-time job in the summer. When I was there I was responsible for fabricating combine bins, underground mining equipment, and repairing all heavy machinery from the mines.</p>
    </div>
  </div>

  <div class="tl-item">
    <div class="tl-bg" style="background-image: url(https://dl.dropboxusercontent.com/s/30efgs0hfswyqbi/plymale.png?dl=0"></div>
    <div class="tl-year">
      <p class="f2 heading--sanSerif">2016</p>
    </div>

    <div class="tl-content">
      <h1 class="f3 text--accent ttu">Plymale Auto Repair</h1>
      <p>Plymale was a general automotive repair shop in Absarokee Montana. When the welding shop was slow I would drive over to Plymales shop to learn more about in automotive industry. I learned how to performed general automotive to include engine, transmission, and wire harness repairs. Since I have a welding background I was responsible for welding custom fabrications on light size to commercial size automobiles.</p>
    </div>
  </div>

  <div class="tl-item">
    <div class="tl-bg" style="background-image: url(https://placeimg.com/800/800/nature)"></div>
    <div class="tl-year">
      <p class="f2 heading--sanSerif">2017</p>
    </div>

    <div class="tl-content">
      <h1 class="f3 text--accent ttu">InboundRX</h1>
      <p>InboundRX is a marketing company specializing in pharmacies. I applied as a Intern from Epicodus. While I was there I learned how to write better tests. I helped contributed to two projects. I helped architecture planning for the automation project management application. The first application is an automation project management, I helped by writing tests, fixing bugs, and refactoring. The second app is perimeter based sales tool where I helped write BDD tests, fixed bugs. I also implemented pair-programing with the lead developer.</p>
    </div>
  </div>
</section>

app/views/contacts/new.html.erb
<%= render('shared/nav') %>

<section id="intro">
  <br>
<%= render 'shared/flash_message' %>
  <div class="center-text">
    <h5>Welcome To My Site!</h5>
    <h1>It's Nice To Meet You</h1>
  </div>
</section>

<section class="picture">
  <div class="profile-img">
    <%= image_tag('https://dl.dropboxusercontent.com/s/93253ko0dwby551/me.jpg?dl=0') %>
  </div>
</section>

<section id="about" class="row">
  <div class="container">
    <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-sm-12">
      <p class="text-center">
        Hello my name is Kevin Finley. I was raised on my family's farm. Working on the farm I have learned what hard work and dedication was at a young age. In middle and high school, I had a few part time jobs. I moved to Portland from Montana for better job opportunities and to be close with my brother. His partner recommended me to a local boot camp called Epicodus. I took the Ruby on Rail course. I am super excited to apply what I have obtained from Epicodus and keep learning!
      </p>
      <hr>
      <h1 id="top-pad" class="text-center">My Journey</h1>

      <p>
        When I was in middle school everyone in my class had to do a science project. I wasn't interested in plants, animals, or chemicals. So, I asked my middle school teacher for any suggestions. Unfortunately she would not give me any suggestions. During the lunch period I ran into the high school science teacher (which was my wrestling coach). He knew I like computers so he recommended me a website filled with computer science topics for me. I saw this link called "Coding an Alphabetizer" and next to it, in bold said "HARD". I don't remember what the description was but the goal was for letters and words to be in alphabetical order.
      </p>

      <p>
        My middle school teacher tried to discourage me from it. After three days of sweet talking, she gave me the okay. I had a month to work on this project. So the first two weeks I was learning HTML and CSS. You are probably going to get a kick out of this, the text editor I chose was Notepad on windows. Then for the remaining time I was learning JavaScript. Throughout the project I realized I had an interest in coding.
      </p>

      <p>
        When we presented our projects, my middle school teacher was amazed that I had a working application. So, after explaining my code to three judges. I placed in third so that meant I got a blue ribbon then moved on state. After state, I did not pursue coding but right after graduating high school I moved to Portland and attended to Epicodus!
      </p>
      <div id="top-pad" class="text-center">
        <hr>
        <h1>Showcase Projects</h1>
      </div>
    </div>
  </section>

  <%= render('contacts/projects') %>

  <section id="top-pad" class="row">
    <div class="container">
      <div class="col-lg-8 offset-lg-2 text-center">
        <hr>
        <h1>Work Experience</h1>
      </div>
    </div>
  </section>


  <%= render('contacts/time-line') %>

  <%= render('contacts/footer') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kevin Finley</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css" media="screen" charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=Raleway|Montserrat|Noto+Serif" rel="stylesheet">
  </head>

  <body>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= yield %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-98444277-1', 'auto');
ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/shared/_blogfooter.html.erb
<div class="col-md-12 page-body margin-top-50 footer">
  <footer>
    <ul class="menu-link">
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Home', root_path %></li>
    </ul>

    <p>© Copyright 2017 Kevin Finley. All rights reserved.</p>
  </footer>
</div>

app/views/shared/_flash_message.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded sticky-top">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">
    <img src="https://dl.dropboxusercontent.com/s/q794yemuv2jr53v/KFTWOTWO.png?dl=0" width="160" height="30" class="d-inline-block align-top" alt="kftwotwo">
  </a>

  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'Blog' , blogs_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://drive.google.com/open?id=0B46chqA4u5qqYlhfdmlFd1hLWEE" target="_blank">Resume</a>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_sidenav.html.erb
<div class="col-lg-3 col-md-3">
  <div class="about-fixed">

    <div class="my-pic">
      <%= image_tag('https://dl.dropboxusercontent.com/s/ud6ssjhp1kya5so/blog.jpg?dl=0') %>
      <a href="javascript:void(0)" class="collapsed" data-target="#menu" data-toggle="collapse"><i class="icon-menu menu fa fa-bars"></i></a>
      <div id="menu" class="collapse">
        <ul class="menu-link">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Contact", root_path %></li>
          <li><%= link_to "Work", root_path %></li>
        </ul>
      </div>
    </div>

    <div class="my-detail">
      <div class="white-spacing">
        <h1>Kevin Finley</h1>
        <span>Ruby on Rails Developer</span>
      </div>
      <ul class="social-icon">
        <li><a href="#" target="_blank" class="twitter"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#" target="_blank" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
        <li><a href="#" target="_blank" class="github"><i class="fa fa-github"></i></a></li>
      </ul>
    </div>
  </div>
</div>

app/views/static_pages/_form.html.erb
<%= form_for @contact_kevin, class: 'form-horizontal' do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group ">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: 'btn'%>
<% end %>

app/views/static_pages/index.html.erb
<section id="intro">
  <div class="center-text">
    <h5>Welcome To My Site!</h5>
    <h1>It's Nice To Meet You</h1>
  </div>
</section>

<section class="picture">
  <div class="profile-img">
    <%= image_tag('https://dl.dropboxusercontent.com/s/f8kkf7sqlh18n1t/20941128.png?dl=0') %>
  </div>
</section>

<section id="about" class="row">
  <div class="container">
    <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-sm-12">
      <p class="text-center">Hello my name is Kevin Finley. I was raised on my family's farm. While working on the farm hard work and dedication was instilled in me at a young age. In middle and high school I had part time jobs. I moved to Portland from Montana for better job opportunities and to be close with my brother. His parterner recommend me to a local boot camp called Epicodus. I took the Ruby on Rail course.</p>
      <h1 class="text-center">My Journey</h1><hr>

      <p>When I was in middle school everyone in my class had to do a science project. I wasn't interested in plants, animals, or chemicals. So I asked my middle school teacher for any suggestions. Unfortunately she would not give me any suggestions. During the lunch period I ran into the high school science teacher (which was my wrestling coach). He knew I like computers so he recommended a website filled with computer science topics for me. I saw this link called "Coding an Alphabetizer" and next to it, in bold said "HARD". I don't remember what the description was but the goal was for letters and words to be in alphabetical order</p>

      <p>My middle school teacher tried to discourage me from it. After three days of sweet talking, she gave me the okay. I had a month to work on this project. So the first two weeks was learning HTML and for my text editor I used Notepad on windows. Then for the remaining time I was learning JavaScript and CSS. Throughout the project I realized I had a interest in coding.</p>

      <p>When we presented our projects, my middle school teacher was amazed that I actually had a working application. So after explaining my code to three judges. I placed in third so that meant I got a blue ribbon then moved on state. After state I did not pursue coding trough middle and high school. But right after graduating high school I moved to Portland to attend to Epicodus!</p>
      <div class="text-center">
        <h2>Tech meetups</h2><hr>
        <p>Portland Ruby Brigade</p>
        <p>Future Talks</p>
        <p>New Tech PDX</p>
        <h1>Showcase Projects</h1><hr>
        <p>Here are a few projects I have made and contributed to.</p>
      </div>
    </div>
  </section>

<%= render('static_pages/projects') %>

<section id="about" class="row">
  <div class="container">
    <div class="col-lg-8 offset-lg-2 text-center">
      <h1>Work Experience</h1><hr>
      <p>I have done alot of add jobs for the Absarokee community!</p>
    </div>
  </div>
</section>


<%= render('static_pages/time-line') %>

<section id="contact">
  <div class="contact-section">
    <div class="container text-center">
      <h2>Contact Me</h2>
      <p>Feel free to shout me a message by filling out the contact form.</p>
      <div class="row">
        <div class="col-lg-6 col-sm-12">
          <%= render('static_pages/form') %>
        </div>

        <div class="col-lg-6 col-sm-12">
          <h3>My Social Sites</h3>
          <ul class="list-inline">
            <li><a href="/" class="btn btn-outline-info"><i class="fa fa-twitter"> <span class="network-name">Twitter</span></i></a></li>
            <li><a href="/" class="btn btn-outline-secondary"><i class="fa fa-github"> <span class="network-name">GitHub</span></i></a></li>
            <li><a href="/" class="btn btn-outline-primary"><i class="fa fa-linkedin-square"> <span class="network-name">Linkedin</span></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>